### ISSUE TITLE
Smaller datasets are needed

### ISSUE THREAD

**Issue by jblezoray** [matchID-project/examples#3]
I think smaller datasets would make testing the project easier.

For instance, the dataprep_deaths recipe on the 1355745 lines of deaths.txt.gz is running since more than 1.5 hour on my computer (8cores i7@3.60GHz, 16G RAM).  It would be interresting to have smaller datasets to ease the user experience while testing the product. 

At least I had time to read the documentations :-) but I'm a bit concerned when I see this in the "clients_x_deaths" recipe : 

> It should take about 2 hours to run it for 1M x 1M with a 16vCPUx32Go and 3 elasticsearch nodes.

:-)

**Comment by rhanka** [comment]
thanx for your return.

theses datasets were publish to handle a realistic usecase but you re right : we needed smaller use case just for the demo effect

new datasets has been posted two weeks with a simple tutorial for playing in ten minutes. i d be glad you could review it

**Comment by rhanka** [comment]
here is the tuto https://matchid-project.github.io/quick_tutorial
